# Dongle connects to both keyboard halves over BLE
CONFIG_ZMK_SPLIT_BLE_CENTRAL_PERIPHERALS=2
CONFIG_BT_MAX_CONN=7
CONFIG_BT_MAX_PAIRED=7

# Enable ZMK Studio support (central/dongle only)
CONFIG_ZMK_STUDIO=y
CONFIG_ZMK_STUDIO_LOCKING=n
CONFIG_ZMK_STUDIO_LOCK_ON_DISCONNECT=n
CONFIG_ZMK_BLE_EXPERIMENTAL_CONN=y
